# Generated by Django 5.1.1 on 2024-09-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCreationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_heading', models.CharField(max_length=100, unique=True)),
                ('course_tags', models.CharField(blank=True, max_length=60, null=True)),
                ('course_thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('course_description', models.TextField(blank=True, max_length=500)),
                ('course_instructor', models.CharField(max_length=50)),
                ('course_price', models.IntegerField()),
            ],
        ),
    ]
