# Generated by Django 5.1.1 on 2024-09-17 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecreationmodel',
            name='course_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='CourseDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_project_num', models.CharField(max_length=100)),
                ('course_related_images', models.ImageField(blank=True, null=True, upload_to='course_dets_img/')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='course_app.coursecreationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutlineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_heading', models.CharField(max_length=100)),
                ('outline_desc', models.TextField(default='Enter outline here')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlines', to='course_app.coursecreationmodel')),
            ],
        ),
    ]
