# Generated by Django 5.1.1 on 2024-09-17 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_coursecreationmodel_course_id_coursedetailsmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_project_num', models.CharField(max_length=100)),
                ('course_related_images', models.ImageField(blank=True, null=True, upload_to='course_dets_img/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='course_app.coursecreationmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseDetailsModel',
        ),
    ]
