# Generated by Django 5.1.1 on 2024-09-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_alter_courseoutlinemodel_outline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutlinemodel',
            name='outline_id',
            field=models.IntegerField(verbose_name=255777),
        ),
    ]
