# Generated by Django 5.1.1 on 2024-09-17 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_alter_courseoutlinemodel_outline_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoutlinemodel',
            name='outline_id',
        ),
    ]
