# Generated by Django 5.1.1 on 2024-09-17 03:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_remove_courseoutlinemodel_outline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutlinemodel',
            name='outline_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
