# Generated by Django 5.1.1 on 2024-09-17 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0008_courseoutlinemodel_outline_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoutlinevideomodel',
            name='course',
        ),
        migrations.AddField(
            model_name='courseoutlinevideomodel',
            name='course_outline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outline_videos', to='course_app.courseoutlinemodel'),
        ),
        migrations.AlterField(
            model_name='courseoutlinemodel',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outlines', to='course_app.coursecreationmodel'),
        ),
    ]
