# Generated by Django 5.1.1 on 2024-09-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_remove_courseoutlinevideomodel_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutlinevideomodel',
            name='course_video_description',
            field=models.TextField(default='wrte your vidoe description here'),
        ),
    ]
