# Generated by Django 5.1.1 on 2024-09-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_courseoutlinevideomodel_course_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprojectsmodel',
            name='course_related_images',
            field=models.FileField(blank=True, null=True, upload_to='course_project_intro/'),
        ),
    ]
