# Generated by Django 5.1.1 on 2024-09-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0011_alter_courseprojectsmodel_course_related_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprojectsmodel',
            name='course_related_images',
            field=models.ImageField(blank=True, null=True, upload_to='course_project_intro/'),
        ),
    ]
