# Generated by Django 5.1.1 on 2024-09-18 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0012_alter_courseprojectsmodel_course_related_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFieldRealtedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_short_title', models.CharField(max_length=50)),
                ('course_level', models.CharField(max_length=50)),
                ('course_related_image', models.ImageField(blank=True, upload_to='course_related_photo')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_field_related_content', to='course_app.coursecreationmodel')),
            ],
        ),
    ]
